### ISSUE TITLE
4 note auto acting oddly

### ISSUE THREAD

**Issue by prankX02** [errorcodexero/allegro2024cmd#2]
During the 4 note auto we collect the note but instead of going straight back to the speaker and shooting, it drives forward a little before coming back and shooting

**Comment by sjcbulldog** [comment]
A change was made to ensure the initial heading for a path goes from the current robot position to the next point on the path, instead of the direction the robot is pointing.  This eliminates the hitch in the path that goes forward first and then loops back to the destination direction.
